### ISSUE TITLE
[Enhancement] Add support for units

### ISSUE THREAD

**Issue by scjoiner** [Vonage/Grafana_Status_panel#11]
It would be very useful to be able to apply the standard Grafana units to each measurement in the panel, especially on a per-measurement basis. Our use case is monitoring server hardware (CPU, memory, disk, IO, etc.).

**Comment by Maahaax** [comment]
+1 on this.
That would be great! I'm using the Panel for displaying bandwidth-usage of several switches so the units inclusive the specific conversions would be great.

**Comment by PeteBa** [comment]
I think this should be closed by PR #55 Units of Measure, Decimals and Date formatting ?
