### ISSUE TITLE
Feature request: Option to inverse

### ISSUE THREAD

**Issue by NadirHamburg** [Vonage/Grafana_Status_panel#12]
I need an indicator that goes to red in case that a value goes below a threshold and not above. 

This could be done by changing the css, but would impact all panels. An additional configuration option should be easy to implement and would be the right way to go.

Kind regards,
Nadir

**Comment by TomerAmirV** [comment]
Hello @NadirHamburg ,

If I understand you correctly, then the solution is already implemented. just put a critical threshold lower than the warning threshold, and that should work.

Please reopen the issue if it didn't and supply more details.
