### ISSUE TITLE
link panel title for opening other dashboard

### ISSUE THREAD

**Issue by wilfrid-dubreuil** [Vonage/Grafana_Status_panel#133]
Hello

I have problem when I create a link for a new dashboard 
1 - in general / drilldown/detail link
these link appear in the dropdown menu in the panel menu
2 - in Options
I inform Panel Title with "LIEN"
3 - I save the change
4 when I click to "LIEN"  in the panel title , I go to the dasboard undefined
How can we have a valid link ?

Thank you for your Help
Data source : elasticsearch V6.5
grafana : V5.4

**Comment by rdxmb** [comment]
same for me with version 1.0.9 and Grafana 5.4.3
