### ISSUE TITLE
Where to set Warning and Critical thresholds (they appear to be missing!)

### ISSUE THREAD

**Issue by jangor** [Vonage/Grafana_Status_panel#16]
In the [README](https://github.com/Vonage/Grafana_Status_panel/blob/master/README.md) it says in the 3rd item on **How to use**: Go the the Options tab, and enter the `Warning` and `Critical` thresholds for each of your queries

My Options tab only shows:

- Panel Title
- Remove Prefix

I cannot find the threshold settings in any of the tabs (`General` `Metrics` `Options` `Time range`)

My (repeated) status panels are shown green (and only geen). Furthermore my query shows a correct graph when clicked on the `Link to Graph in Prometheus`

Can it be caused by the `Panel data souce` which is `Prometheus`?

## Version Info

- I am using Grafana v4.1.1 
- *Same with Grafana v3.1.1 (commit: a4d2708)*
- The status_panel is version 1.0.0
- Query on Prometheus

**Comment by erezzarum** [comment]
Same goes for graphite

**Comment by TomerAmirV** [comment]
Hi and thanks for contacting us!

Currently, the panel was only tested against influxDB. (it's also stated in the README file)
I would be happy to add support for any data source, but unfortunately, we are currently not using other data source, so I don't have what to test against.

Manny people request support for other data sources, so you are more than welcome to fork us and make a pull request if you wish.

**Comment by GPegel** [comment]
@TomerAmirV I have a couple of environments running Zabbix, RELK stack and Grafana all together. How can I contribute for testing purposes because I really would love to have a pannel like this with Zabbix as a datasource. So if my help is appreciated, please let me know.

**Comment by TomerAmirV** [comment]
Hi @GPegel ,

If there is a way that you can let me connect to your Zabbix server as a data source, it would be very helpful. Otherwise, it would be hard for me to fix whatever is not working since I don't know what it is.

I did just release a new version that fixed the issue with Graphite that might have also helped with Zabbix, but I did not test it with it.

If you could install the new version (it is currently pending approval by Grafana) and tell me if it worked, that could also help.

**Comment by GPegel** [comment]
@TomerAmirV yes I have a test Zabbix server up and running. I will send you the credentials later via mail so you are able to test. And I will test the new release and will let you know.
