### ISSUE TITLE
Stat_Panel Link not working with Grafana 6.6.2

### ISSUE THREAD

**Issue by ramchinthamsetty** [Vonage/Grafana_Status_panel#163]
Hi team,

Grafana Stat panel is not working with the reference link when we click on the panel. It is redirecting to the undefined page.
Referring to the panel links configuration: 
After configuration of URL, once I click on the panel it is redirecting to the error page. It works well with Grafana 6.2 version.
![image](https://user-images.githubusercontent.com/33153131/80352043-ecef5f00-8890-11ea-8cbf-89c56acba587.png)

**Comment by panditvaddi** [comment]
Hi Team,

I do have similar issue, I am facing the issue in 6.4.2 and even in 6.6.2.

**Comment by chris-heath** [comment]
This issue is resolved with v1.0.10. Please open a new issue if you run into any additional problems.
