### ISSUE TITLE
StatusByGroupPanel not working with Grafana v6.7.3

### ISSUE THREAD

**Issue by keya215** [Vonage/Grafana_Status_panel#164]
Hi Team,

Status By Group Panel is not working wih CloudWatch Data Source. While creating dashboard I'm getting below error. 
"Panel rendering error, Cannot read property 'slice' of undefined" 
![Screenshot (196)](https://user-images.githubusercontent.com/50591811/80528057-50e25800-8963-11ea-94ad-f046f80721e0.png)

Grafana version : v6.7.2

**Comment by guliangsi** [comment]
Hi, 
Same problem "Cannot read property 'slice' of undefined" with Prometheus Datasource and Grafana v6.7.2

Thanks for your help.
Regards

**Comment by keya215** [comment]
@guliangsi Try degrading docker version to 6.5.0. That worked for me.
