### ISSUE TITLE
Plugin alive?

### ISSUE THREAD

**Issue by chforster** [Vonage/Grafana_Status_panel#167]
Hello everybody,

I just wanted to know if this plugin is still alive and maintained by someone.
I mean there are a lot of open pull requests and especially the Problem with Grafana > 6.7 ( #161 ) is from my point of view very urgent.

Nevertheless the last Version 1.0.9 was released in November 2018!

To add also some positive feedback: I like this plugin because it supports features I haven't found within other plugins or standard features I'd not like to miss when upgrading Grafana.

**Comment by MalfuncEddie** [comment]
Also wondering this. Grafana 7 breaks the panel. I am wondering if I should migrate to the https://grafana.com/grafana/plugins/grafana-polystat-panel but it does not support tabel queries yet.

**Comment by chris-heath** [comment]
This issue is resolved with v1.0.10. Please open a new issue if you run into any additional problems.
