### ISSUE TITLE
Facing problems with status panel for grafana version 7.0

### ISSUE THREAD

**Issue by sainuthaha** [Vonage/Grafana_Status_panel#168]
With grafana version 7.0, status panel is giving errors, here under the options tab , there is no option to set the threshold type, 
<img width="361" alt="Capture" src="https://user-images.githubusercontent.com/24546941/82983594-03164980-a00e-11ea-9a1b-b67710f8118e.PNG">

Do we have any workaround.

**Comment by ktibi** [comment]
Hello,

you can find workaround here : https://github.com/Vonage/Grafana_Status_panel/issues/159

**Comment by imavroukakis** [comment]
> Hello,
> 
> you can find workaround here : #159

Thanks @ktibi will try it out. A bit off-topic but do you know if this panel works with Prometheus as the data source?

**Comment by dmaes** [comment]
I used it successfully with Prometheus on an older Grafana install. Did a fresh Grafana 7.0 install, but can't get it to work this time.

**Comment by chris-heath** [comment]
This issue is resolved with v1.0.10. Please open a new issue if you run into any additional problems.
