### ISSUE TITLE
TypeError: panelWidth is undefined

### ISSUE THREAD

**Issue by dh3wr** [Vonage/Grafana_Status_panel#169]
When selecting the plugin and changing any setting of the query this happens. Grafana 7.0.1

![grafik](https://user-images.githubusercontent.com/16710361/83305802-b5fac900-a201-11ea-9c06-9b9e3e5d0cc8.png)

**Comment by f-israel** [comment]
+1

same here, except it's triggering even without query change (Grafana 7.0.3)

**Comment by EspenHe** [comment]
+1

**Comment by ffgalindo** [comment]
+1

Same issue in ﻿Grafana 6.7.3

**Comment by Ben0it** [comment]
+1

Same issue with Grafana 7.0.3 and vonage-status-panel v1.0.9.

**Comment by stlinux** [comment]
Dear, do you have any answer to this problem?

**Comment by chris-heath** [comment]
This issue is resolved with v1.0.10. Please open a new issue if you run into any additional problems.
