### ISSUE TITLE
TypeError: Cannot read property 'slice' of undefined

### ISSUE THREAD

**Issue by miluksandrades** [Vonage/Grafana_Status_panel#171]
After selecting the plugin in grafana, it shows this error:
TypeError: Cannot read property 'slice' of undefined

    in t
    in t
    in div
    in div
    in div
    in div
    in div
    in t
    in t
    in t
    in div
    in Ma
    in div
    in on
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

Grafana: 7.0
OS: Ubuntu Server 20.04

**Comment by Plouviet** [comment]
I have the same issue with Grafana 7.0

**Comment by abrekhov** [comment]
Same issue on Grafana v6.7 and higher. 6.6 is ok

**Comment by ablecable** [comment]
Same issue on Grafana v7.0.3

**Comment by max-kernel** [comment]
and I have the same issue with Grafana Grafana v7.0.3((

**Comment by stefanwendelmann** [comment]
Same on Grafana v7.1.3 (5723d951af)

**Comment by chris-heath** [comment]
This issue should be resolved with v1.0.10.  Please open a new issue if you run into any other problems.
