### ISSUE TITLE
Unable to see status panel values on Grafana 7

### ISSUE THREAD

**Issue by ashish-infini** [Vonage/Grafana_Status_panel#172]
Just upgraded grafana from 6 to 7 and this plugin seems to be not working for some reason.

I am using Prometheus and Blackbox exporter for service status.

**Comment by vinaykrishnaAMD** [comment]
This panel is not working with Grafana7.0. Even after upgrade it still shows version is 1.0.8
![image](https://user-images.githubusercontent.com/67149792/85127263-bc9ebe00-b24c-11ea-9465-9571d851fc14.png)

**Comment by nigelhorne** [comment]
It's not been updated for 2 years.  I don't think this is supported any more.  I can't get any data to show either.

**Comment by Scappz** [comment]
Is there any alternative plugin out there?

**Comment by rbrayner** [comment]
It is a really useful plugin.

**Comment by niar68** [comment]
It is s a great plugin and I use it as a heatmap and it working really well, but not on version 7.*. 
I've tried to put the plugin under allow_backend_plugin, but without any luck.
Is there any plan to get it signed, so it usable on newer versions of Grafana.

**Comment by chris-heath** [comment]
This issue should be resolved with v1.0.10.  Please open a new issue if you run into any additional problems.
