### ISSUE TITLE
Not working with Zabbix as datasource

### ISSUE THREAD

**Issue by godmarck** [Vonage/Grafana_Status_panel#25]
Hi.
I know it's not supposed to be included, but it seems like a very useful panel for Zabbix.
So far I was able to select the metrics as if it was supported but then I get no values.
Not sure if this is the right way to do such a request, please delete if inapropriate.

**Comment by TomerAmirV** [comment]
Hello @godmarck ,
This is a very good way to submit a request, but this is a duplicate of #9 which I started working on. It will take me a bit more time, but I will update that issue as soon as it's ready.

**Comment by godmarck** [comment]
Thanks a lot for your response and hard work!
