### ISSUE TITLE
"Show Metric" check box  

### ISSUE THREAD

**Issue by elifu** [Vonage/Grafana_Status_panel#36]
Hi
Uncheck the "Show Value" checkbox show the alias but not the value
Click on the eye icon hide the metric at all with no way to set a threshold for this field. 
What we look for is a mix of the two above. Means not showing the value and the metric . However, be able to set a threshold color according to the field value.
Please advise.
Thanks,
Eli

**Comment by TomerAmirV** [comment]
Hello Eli,

We do not support your use case currently since we wanted to show an overview of all the problems with the thing you are monitoring.

If you want, you could add the functionality and make a pull request. I'll be happy to assist if you want 😄

**Comment by YehonatanVonage** [comment]
Hi @elifu,
Your problem is resolved in version 1.0.7:
https://github.com/Vonage/Grafana_Status_panel/releases/tag/1.0.7
