### ISSUE TITLE
Threshold for numbers is not working

### ISSUE THREAD

**Issue by bashnesnos** [Vonage/Grafana_Status_panel#43]
Hi guys,

Thanks for the great work, it seems this status panel is the only one which can aggregate multiple metrics.

Though it doesn't fire thresholds if I specify them as numbers. I've found out that it happens due to incorrect propagation of the threshold values into the `parseThresholds` method, i.e. they are passed as strings anyway, so when you do the checking of `angular.isNumber` it's always a string. I'm on grafana 4.2.2 by the way.

Here is a work around that helped to fix it in meanwhile:

	{
		key: "parseThresholds",
		value: function parseThresholds(metricOptions) {
			var res = {};

			res.warnIsNumber = NUMBER_REGEXP.test(res.warn);
			if (res.warnIsNumber) {
				res.warn = parseFloat(metricOptions.warn);
			} else {
				res.warn = metricOptions.warn;
			}

			res.critIsNumber = NUMBER_REGEXP.test(res.crit);
			if (res.critIsNumber) {
				res.crit = parseFloat(metricOptions.crit);
			} else {
				res.crit = metricOptions.crit;
			}
			return res;
		}
	}

**Comment by TomerAmirV** [comment]
Thanks!
We're on it. Expect a fix soon

**Comment by YehonatanVonage** [comment]
Hi,
Thanks for finding this bug. A fix already pushed to master, and will be available in the new release (1.0.3) in Grafana soon.

**Comment by bashnesnos** [comment]
Thanks guys, works like a charm now. Should I close the issue, or it's up to you?

**Comment by TomerAmirV** [comment]
We waited until Grafana published our changes, which now they did, so I'll close it.

Thanks again 😄
