### ISSUE TITLE
Adding a detail link (absolute) to a panel turns panel title into an invalid link

### ISSUE THREAD

**Issue by maxbechtold** [Vonage/Grafana_Status_panel#45]
When I add an absolute link (say www.github.com) to a status panel (General tab), the link appears as an annotation/popup.

However, the panel title also becomes clickable, but leads to the local URL [this-grafana]/dashboard/undefined?undefined

I guess it was intended for the Panel title to also become a link to www.github.com? This would be my expected behaviour, as the popup in the left upper corner is a bit too subtle.

Context:
Grafana 4.1.2.
Status Panel 1.0.3

**Comment by maxbechtold** [comment]
To clarify this, by 'panel title' I mean the one you can configure on the Options tab which is displayed in the panel center.

I'm not referring to the 'title' that can be set on the General tab which is displayed at the top center of the panel

**Comment by TomerAmirV** [comment]
What type of link did you choose? `absolute` or `general`?

**Comment by maxbechtold** [comment]
As I wrote, the issue appears with `absolute` links.
`Dashboard` links work better, as the centered panel title becomes the same clickable link as the annotation.

**Comment by TomerAmirV** [comment]
Thanks!
I fixed this bug and it will be released in the next version

**Comment by maxbechtold** [comment]
Thank you as well!
