### ISSUE TITLE
Drill-down links open in new tab even without selecting this option

### ISSUE THREAD

**Issue by maxbechtold** [Vonage/Grafana_Status_panel#47]
Defining drill-down links on a status panel makes its title (the center text) clickable.
I'd like this to use to link to detail dashboard, and I want it to open in the current tab. So I _don't_ check the option "Open in new Tab"

Still, the link will open in a new tab (Firefox) or new browser window (Internet Explorer).

Also, while I don't define any Url parameters, and don't include time range or variables, the link ends with `?undefined`

Can you take a look into this?
Aside from these issues, this panel type suits our need really well, so thumbs up!

**Comment by TomerAmirV** [comment]
Thanks for your report!
I fixed this issue and it will be released in the next version 😄
