### ISSUE TITLE
Datasource for Grafana Status Panel

### ISSUE THREAD

**Issue by django-kz** [Vonage/Grafana_Status_panel#48]
HI ! 
Thank you for your status panel, i think that's exactly what i need, but I couldn't export any data from zabbix to this panel.  Have you tested it? I mean Zabbix plugin for Grafana, it provides "Zabbix Datasource" within.    Is there any way to add this functionality ?

**Comment by TomerAmirV** [comment]
Hi!
This is a known issue and will take some time to fix.
please see #9 

If you want, you can try fixing it yourself and make a pull request. 😄

**Comment by django-kz** [comment]
I thought about fixing it, I'll try :) Can we contact somehow, so i can ask questions( if i have them)  about your project ?

**Comment by TomerAmirV** [comment]
Sure :)
you can send me an email (listed in my profile). I'll help you as much as I can...
