### ISSUE TITLE
Show disable for no data - doesn't work

### ISSUE THREAD

**Issue by alekseyp** [Vonage/Grafana_Status_panel#51]
Hi there,

I'm using 
Plugin version: 1.0.3
Grafana: v4.2.0 (commit: 349f3eb)
Influxdb: 1.2.2

and `Show disable for no data` options doesn't work. it always shows dead host as green.

That's the query browser sends to influxdb

```
SELECT mean("usage_idle") * -1 + 100 FROM "cpu" WHERE "cpu" = 'cpu-total' AND "host" =~ /^ SERVERNAME $/ AND time > now() - 60s;SELECT "used_percent" FROM "mem" WHERE "host" =~ /^ SERVERNAME $/ AND time > now() - 60s;SELECT mean("percent_packet_loss") FROM "ping" WHERE "host" =~ /^SERVERNAME$/ AND "url" = '45.32.86.215' AND time > now() - 60s
```

and here is the return.

```
{
    "results": [
        {
            "statement_id": 0
        },
        {
            "statement_id": 1
        },
        {
            "statement_id": 2
        }
    ]
}
```

I've ran the same query via CLI and no data was returned either.

Screenshot: https://www.evernote.com/l/AAq0aLsiJEBIeZFm8uSi7OnaWD2eypfOeW4

Any ideas?

**Comment by YehonatanVonage** [comment]
Thanks for your report!
I fixed this issue and it will be released in the next version.
