### ISSUE TITLE
[Feature request] Restricting number of metrics displayed on panel to preserve layout

### ISSUE THREAD

**Issue by maxbechtold** [Vonage/Grafana_Status_panel#53]
I understand that the idea of Status panel is to aggregate many metrics into a single panel.
But when too many of these metrics have an issue, the list in the panel gets too long and the panel stretches vertically.

This breaks the layout and reduces the transparency of the whole board, as rows grow very high and won't fit on a single screen at some point. 

I'd love an option to restrict the metrics displayed in the panel, e.g. restriction of 5 failing metrics to 3 could look like:
`My Status Panel`
`Red Metric 1`
`Red Metric 2`
`Red Metric 3`
`(... and 2 more)`

Alternative: Restriction of a panel to a maximum height (the property `height` of a Status panel cannot be used for that currently), where extraneous metrics could simply be cut off.

What do you think of this?

**Comment by YehonatanVonage** [comment]
Hi,
I added the feature, and you will see it in the upcoming version (1.0.5)

**Comment by maxbechtold** [comment]
Wow, that was fast! :)

What alternative did you choose?

**Comment by YehonatanVonage** [comment]
The first one, with max alerts to show

**Comment by maxbechtold** [comment]
Hi,
any idea when this will be released in a new version?

**Comment by TomerAmirV** [comment]
Hi @maxbechtold,

Lately, we are working on other things, so we don't have much time to work on this plugin.
I'll try to find some time to close pull requests and prepare the next version.
