### ISSUE TITLE
Regex filtering seems not to work

### ISSUE THREAD

**Issue by nikos** [Vonage/Grafana_Status_panel#62]
The javascript seems in the current version to throw an error (tested with Chrome v58) and seems like the input variable is not set and therefore the regular expression matching seems to be unhappy:

Background: I was trying to round a float (coming from a sumSeries graphite operation) and limit the number of digits displayed in the status panel to ease reading the status for multiple servers.

```
boot.d709d8d5.js:51 TypeError: Cannot read property 'match' of null
    at numberOrTextFilter (/public/plugins/vonage-status-panel/status_ctrl.js?bust=1497007999965:131)
    at fn (eval at compile (boot.d709d8d5.js:53), <anonymous>:4:321)
    at boot.d709d8d5.js:51
    at o.$digest (boot.d709d8d5.js:51)
    at o.$apply (boot.d709d8d5.js:52)
    at boot.d709d8d5.js:52
    at f (boot.d709d8d5.js:50)
    at boot.d709d8d5.js:50
```

<img width="844" alt="screen shot 2017-06-09 at 13 44 03" src="https://user-images.githubusercontent.com/31314/26974148-476ec2c8-4d1a-11e7-8494-14b10ff0a801.png">

**Comment by TomerAmirV** [comment]
Hi,

I checked and I managed to reproduce.
I create a fix and add it to the next version.

Thanks!
