### ISSUE TITLE
Add the support of 'Invert Order' in threshold values similar to singelstat panel.

### ISSUE THREAD

**Issue by digrich** [Vonage/Grafana_Status_panel#7]
We want to define threshold when certain values are going down.

**Comment by TomerAmirV** [comment]
Hello @digrich 

The plugin does support decreasing values. If you enter a Critical threshold lower than the Warning threshold, the plugin will recognize that, and automatically refer to your values in a decreasing manner.

If it does not work for you, please feel free to re-open this issue, and supply more details please.
