### ISSUE TITLE
[Feature Request] Configurable text colour

### ISSUE THREAD

**Issue by royemmerich** [Vonage/Grafana_Status_panel#70]
Thanks a ton for this great panel!

We make use of both the dark and light Grafana themes (depending on the customer). With the dark theme the text is clearly legible:

![screen shot 2017-08-24 at 12 31 08](https://user-images.githubusercontent.com/3904395/29662626-4a58849e-88c8-11e7-840e-02e6ebd37e86.png)

However with the light theme it's not:

![screen shot 2017-08-24 at 12 30 30](https://user-images.githubusercontent.com/3904395/29662620-445521c4-88c8-11e7-884f-e46c67d50954.png)

It would be super if you could include an option to change the text colour.

**Comment by TomerAmirV** [comment]
Hi @royemmerich,

Sound like a good idea, could it be solved by #58?
We're about to merge it and add it to the next release
