### ISSUE TITLE
[Feature Request] configurable color for panels.

### ISSUE THREAD

**Issue by nishantsharmajecrc** [Vonage/Grafana_Status_panel#72]
Right now I see there is no way to configure panel colors apart from Warning, Ok and Critical. Is it possible to include a feature to configure panels colors as well?

**Comment by nishantsharmajecrc** [comment]
can some one merge #58 that addresses that feature request

**Comment by TomerAmirV** [comment]
Thanks, for the suggestion!
I approved the pull request and merge it once the previous PR is merged.

**Comment by TomerAmirV** [comment]
Merged and released in 1.0.5
Enjoy 😄
