### ISSUE TITLE
How to set the white text in the green background

### ISSUE THREAD

**Issue by cloudbehl** [Vonage/Grafana_Status_panel#74]
I want to see the text as white in the green background and I am not able to do it. Can someone help me out with this issue?

**Comment by stellasawicki** [comment]
I believe it is a default setup. Make sure in _Options_, under _Threshold Colors_ you have selected _Coloring: Panel_. 
![image](https://user-images.githubusercontent.com/30984108/32304539-6386a7c8-bf70-11e7-9429-891a30af1bf6.png)
Once your metrics are OK (neither Warning nor Critical), you should see white OK on green background.
