### ISSUE TITLE
[Bug] - Grafana status panel is not working after upgrading to grafana v4.6.2

### ISSUE THREAD

**Issue by dudusakharovich** [Vonage/Grafana_Status_panel#86]
Hey,

I've upgraded to Grafana v4.6.2 and also upgraded the status panel to version 1.0.6 but I still receive the following error while trying to load the dashboard which is based on the status panel graphs:

Plugin Error
Fetch error: 404 Not Found Instantiating http://xxxx/public/app/plugins/panel/graph/legend Loading http://xxxx/public/plugins/vonage-status-panel/status_ctrl.js Loading plugins/vonage-status-panel/module

**Comment by dudusakharovich** [comment]
@YehonatanVonage - Hey, Are you aware that the panel is still not working after the fix ?

**Comment by YehonatanVonage** [comment]
@dudusakharovich, I didn't encounter the "404" issue again after upgrading to the latest panel version.

Please check again the usage of the panel (version 1.0.6),
1. Try open the dashboard in another browser
2. Check out if your browser is caching any reference to the old version of the panel
3. Try to re-install the plugin, and checkout that you are not using the old version by mistake

**Comment by dudusakharovich** [comment]
@YehonatanVonage - Hey, You are right it does work, I probably didn't do it in the right order (First plugin upgrade and then Grafana version upgrade).
