### ISSUE TITLE
Incompatible with Grafana 4.6.3?

### ISSUE THREAD

**Issue by choffm** [Vonage/Grafana_Status_panel#92]
Can you please check whether this panel is compatible with Grafana 4.6.3? I upgraded to Grafana 4.6.3 recently and the metrics are not evaluated any more, resulting in an overall "OK" state for all Status Panel panels.

**Comment by haizaar** [comment]
I have Grafana 4.6.3 with Prometheus DS and it does not seem to work as well (didn't have a chance to try it on earlier versions though).

**Comment by Flyweightt** [comment]
Hi 
I cannot load the plugin at all.
grafana:  4.6.3: Debian 4.9.30-2+deb9u3
Status panel 1.0.7
When trying to add the status panel to a dashboard I get:
Plugin Error
Fetch error: 404 Not Found Instantiating http://localhost:3000/public/app/plugins/panel/graph/legend Loading http://localhost:3000/public/plugins/vonage-status-panel/status_ctrl.js Loading plugins/vonage-status-panel/module

Could this have to do with?:   [[https://github.com/grafana/grafana/blob/master/PLUGIN_DEV.md]]

    Webpack: Changed from systemjs to webpack (see readme or building from source guide for new build instructions). Systemjs is still used to load plugins but now plugins can only import a limited set of dependencies. See PLUGIN_DEV.md for more details on how this can effect some plugins.

**Comment by Flyweightt** [comment]
Hi This can be closed. Status panel 1.0.7 and grafana: 4.6.3 are working fine.

Cheers

TIm

**Comment by hackdefendr** [comment]
Same issue with Grafana 5.0 beta 1.

**Comment by mikkop71** [comment]
Actually I have same problem with Graphana 4.6.2 and Status panel 1.0.7.
Although metric values go over the set thresholds everything stays happily in the green zone.
